### PR TITLE
Compare AXML attribute name by resource ID

### PR DESCRIPTION
**Pull request by nonnonstop**
This is porting of https://github.com/WindySha/Xpatch/pull/114.

# Issues

* Due to https://github.com/WindySha/ManifestEditor/pull/6, an AndroidManifest with two appComponentFactory attributes may be created and LSPAppComponentFactoryStub may not be used, causing crash with ClassNotFoundException.
    image
* For the same reason, the original appComponentFactory name is not saved in `assets/lspatch/config.json`.
    image

I saw that some obfuscated apk files cause this bug, so I would very much like to fix it. 😫 

# Steps to reproduce

1. Download [this apk file](https://www.mediafire.com/file/loza6o11wxb6b5w/app-release4.apk/file).
  This apk file has an appfactory class `com.example.testapp.MyAppComponentFactory`.
2. Run LSPatch.

       java -jar jar-v0.3.1-327-release.jar -f -v tmp/app-release4.apk
    Despite the appfactory class being set, the detailed log shows `original appComponentFactory class: null`.
3. View the patched apk with an apk file viewer such as [JADX](https://github.com/skylot/jadx).
    You can see that the aforementioned issues are occurring.
4. Run the patched apk on the device.
    Then you will get the following error log.
    [error.txt](https://github.com/LSPosed/LSPatch/files/9484091/error.txt)

# How to fix

* Update the ManifestEditor to fix AndroidManifest issue.
    * I compiled the committed jar myself. (https://github.com/WindySha/ManifestEditor/commit/aff51233504a52dcb09b5d7e7119bc8b428585f9)
      https://github.com/WindySha/Xpatch/blob/master/xpatch/libs/ManifestEditor-aff5123.jar
*  In ManifestParser.java, compare the attributes of the appfactory name not only as a string but also as a resource ID.
    * The mapping between name and resource ID is defined in [public.xml](https://github.com/WindySha/ManifestEditor/blob/master/lib/src/main/assets/public.xml).

Thank you!

### CODE REVIEW

**Comment by yujincheng08** [comment]
Maybe we should integrate it as a submodule instead.

**Comment by yujincheng08** [comment]
image
不太对

**Comment by nonnonstop** [comment]
`assets/new_keystore` and `assets/public.xml` may be missing in the jar.

before
```
$ unzip -l jar-v0.3.1-327-release.jar | grep assets
        0  2020-01-30 19:10   assets/
     2185  2020-01-28 23:42   assets/new_keystore
   194716  2018-06-14 15:20   assets/public.xml
     2195  2022-08-26 01:22   assets/keystore
        0  2022-08-26 01:48   assets/dex/
     2752  2022-09-04 04:54   assets/dex/loader.dex
   989252  2022-09-04 04:54   assets/dex/lsp.dex
        0  2022-08-26 01:48   assets/so/
        0  2022-08-26 01:48   assets/so/x86/
   213188  2022-09-04 04:54   assets/so/x86/liblspatch.so
        0  2022-08-26 01:48   assets/so/armeabi-v7a/
   131112  2022-09-04 04:54   assets/so/armeabi-v7a/liblspatch.so
        0  2022-08-26 01:48   assets/so/x86_64/
   209448  2022-09-04 04:54   assets/so/x86_64/liblspatch.so
        0  2022-08-26 01:48   assets/so/arm64-v8a/
   173184  2022-09-04 04:54   assets/so/arm64-v8a/liblspatch.so
```
after
```
$ unzip -l jar-v0.3.1-328-release.jar | grep assets
        0  2022-09-04 09:27   assets/
     2195  2022-08-26 01:22   assets/keystore
        0  2022-08-26 01:48   assets/dex/
     2752  2022-09-04 09:27   assets/dex/loader.dex
   989252  2022-09-04 09:27   assets/dex/lsp.dex
        0  2022-08-26 01:48   assets/so/
        0  2022-08-26 01:48   assets/so/x86/
   213188  2022-09-04 09:27   assets/so/x86/liblspatch.so
        0  2022-08-26 01:48   assets/so/armeabi-v7a/
   131112  2022-09-04 09:27   assets/so/armeabi-v7a/liblspatch.so
        0  2022-08-26 01:48   assets/so/x86_64/
   209448  2022-09-04 09:27   assets/so/x86_64/liblspatch.so
        0  2022-08-26 01:48   assets/so/arm64-v8a/
   173184  2022-09-04 09:27   assets/so/arm64-v8a/liblspatch.so
```

**Comment by nonnonstop** [comment]
ok, I fixed it. I will create PR soon.

**Pull request closed without merging**
