### PR TITLE
Implemented "Logs" tab

### PR DESCRIPTION
**Pull request by Chaikew**
Hi!
I implemented the "Logs" tab, now to log something just do it like this:
```diff
- android.util.Log.i("aTag", "A message!")
+ org.lsposed.lspatch.ui.util.ManagerLogging.i("aTag", "A message!")
```

Preview: 
preview

If needed, I speak fluent French and Spanish.

### CODE REVIEW

**Comment by Chaikew** [comment]
Working on: `java.lang.IllegalStateException: Unsupported concurrent change during composition.`

**Comment by yujincheng08** [comment]
thx but this is not the log we need.

**Comment by Dr-TSNG** [comment]
Log page is for modules' logs, instead of manager's

**Comment by Chaikew** [comment]
Alright

**Pull request closed without merging**
